### ISSUE TITLE
Question sur le projet

### ISSUE THREAD

**Issue by Damdoshi** [Paul-Marie/TekAdventure#2]
Bonjour,

Je suis Jason Brillante, le créateur du sujet original de TekAdventure.
J'ai quelques questions à poser, étant tombé la dessus... :-p

![image](https://user-images.githubusercontent.com/14896525/163184153-0308ee7e-8547-475b-8e08-9024179725e9.png)

J'ai pas croisé d'étudiants à l'époque ayant qualifié ce projet de "petit projet ne valant pas le coup de passer beaucoup de temps dessus", du coup ça m'a intrigué et en regardant ton projet, j'ai constaté déjà un jeu ayant l'air chouette, et puis la notation de 4/4 sur le graphe de position, mais je suis incapable de trouver dans ton projet le fichier de description de graphe censé décrire les mouvements possibles (dans un fichier de conf, élément où tu as eu 0/6), du coup je m'interroge, si bien sur tu veux bien répondre à mes quelques questions

Aventure est l'un des projets que je propose encore aujourd'hui et son sujet, c'est précisément le parcours de graphe (Comme NanoTekSpice... un autre de mes crimes) et la mise en place d'un domain specific language, le jeu lui-même n'étant qu'un prétexte.
Est ce qu'Epitech a retiré cette partie du sujet? Est ce que c'est la correction qui s'est concentré sur le jeu? Comment avez vous perçu le projet lorsqu'il est apparu?

**Comment by Paul-Marie** [comment]
Bonjour @Damdoshi et **infiniment désolé** pour la réponse tardive, bien que très actif sur Github je n'avais jamais vu passer la notification de cette issue !

Alors pour résumé, je faisais parti de la promotion 2021 à Epitech Lyon (donc en région), et je ne sais pas comment cela ce passait dans les autres Epitech (Paris ou provincialles), mais pour nous à Lyon les modules d'infographie ce passais comme ceci:

#### B1 - C Graphical Programming (B-MUL-100)
- Wolf3D (création minimaliste du jeux Wolfenstein)
- Wireframe (création de "paysage" à partir de point)

#### B2 - C Graphical Programming (B-MUL-200)
- Raytracer1
- TekAdventure ou Raytracer2

Au second trimestre à Lyon de l'année 2016-2017, ceux ayant réussi le Raytracer1 pouvais s'inscrire au Raytracer2, tandis que les autres étaient forcé de faire le TekAdventure.

> **Note**
> Dans mon cas j'avais la possibilité de m'inscrire au Raytracer2, mais le sujet m'intéressait pas du tout, donc j'ai préféré faire le TekAdventure.

Ensuite, je me souviens très bien de vous, j'étais pas mal actif sur Yammer à l'époque et je viens tout juste de relire le sujet (disponible ci-joint) qu'on avaient eu à Lyon, et effectivement ça parle de graph. Je ne me souviens plus exactement de comment était coder le truc, ni même si cela correspondait bien aux consignes, mais dans mes souvenirs on avait effectivement une map où on avait plusieurs points ou aller et différentes actions à effectuer à ceux-ci.

Je me permets toutefois d'ajouter que ce projet, le `TekAventure`, à été entièrement coder par moi-même en 1 ou 2 semaines seulement avec un autre mate qui s'occupait de la partie "Game design" (c'était le fondateur du fameux groupe Yammer "EpiYammer Play RP", donc c'est lui qui à trouver le concept du jeu et tout). Donc 1 ou 2 semaines de projet seulement avaient été utilisées sur les 2 mois alloués (on était tous en retard sur d'autres projets).

On a eu la meilleure note de ma promotion (Lyonnaise) car on étaient les seuls à venir en soutenance avec un projet "aboutis", tous les autres groupes avaient malheuresement des jeux injouables et non finis, sauf un groupe qui avait tenté un remake de pokémon. Je précise également que les notes de soutenances étaient donné par les AER Tek2, et non le Pédago référent du module, qui était à l'époque `Sébastien MARICHAL` sur Lyon (de souvenir).

> **Warning**
> Aucun des autres groupes de ma promotion lyonnaise n'avait ce concept de "graph", c'était majoritairement des jeux en monde ouvert aux déplacements libre (pour les tekadventure qui compilaient du moins 👀).

La soutenance (lyonnaise) à surtout regarder si notre jeu était "un Point & Click", les AER et pédago parlaient du tekadventure comme d'un jeu point & click avant tout, et je n'ai jamais entendu parler de domain specific language à Epitech (voir le sujet du projet pour confirmer).

Concernant ma perception du sujet Tekadventure, je l'ai vraiment apprécié. Créer un jeu vidéo en Tek1 était vraiment cool, surtout que le projet avait lieu en fin d'année, donc quand nous commencions à vraiment maîtriser la programmation et que nous avions le droit d'utiliser la plupart des fonctions (plutôt que de réutiliser nos fonctions personnalisées). J'en ai gardé un très bon souvenir.

J'aimerais énormément partager des images du jeu sur le repo, mais malheureusement le projet était fait sur BLinux (la dernière année de son utilisation à Epitech, remplacer par une version de fedora l'année suivante) avec une CSFML custom (utilisant le flag `lc_graph_prog_full` au lieu de `lc_graph_prog` et je n'ai jamais réussi à compiler le projet sur une autre bistro que BLinux, j'avais des erreurs de linking ou autres (et je m'estime plutôt très compétent en Linux / Makefile et compilations).
Peut-être que mon ami @Faroito pourraient arriver à le compiler .

J'espère que mes explications vous ont aidé à y voir plus clair !


[B-MUL-151_TekAdventure.pdf](https://github.com/Paul-Marie/TekAdventure/files/10351986/B-MUL-151_TekAdventure.pdf)

**Comment by Damdoshi** [comment]
Ah, bah, aux illustrations et à la langue près, c'est le même sujet. J'imagine que l'importance du DSL devait avant tout découler de nos insistances orales plus que de mes écrits : c'était pas le premier projet à vous amener à concevoir un un format de fichier, mais c'était le plus abouti.

[TekAdventure.pdf](https://github.com/Paul-Marie/TekAdventure/files/10550214/TekAdventure.pdf)

Merci beaucoup pour ta réponse. Je suis content de lire que le projet t'ai plu.
Et félicitation pour y être parvenu dans ces conditions.

Peut-être qu'a l'occasion, il serait possible de faire revivre ton code au delà de BLinux. x)

**Comment by Paul-Marie** [comment]
Et bien sache que je le souhaite aussi, je réessaierai à l'occasion de le recompiler, rien que pour prendre quelque screen pour le `README.md` du repo.
